### ISSUE TITLE
New "functions" ChatGPT API

### ISSUE THREAD

**Issue by AlbertMarashi** [rellfy/openai#8]
### Problem

ChatGPT just released **function calling** API that would be very valuable to have in this crate

https://platform.openai.com/docs/guides/gpt/function-calling

### Solution

Add function call API

**Comment by valentinpurrucker** [comment]
Hey there. I worked on adding the functions api and would like to support you with this crate. I have a question regarding the handling of streaming responses though. 
What's your opinion on handling the function_call response? The format is:
`function_call": {
          "name": String,
          "arguments": String
 }`, where
-  _name_ is the name of the function
-  _arguments_ is a json-object as string with the properties and their values. 

We could expose the arguments to client code with a map, but this would not work with streaming the completions, since streaming just adds the individual characters to the _arguments_ string. But exposing the arguments property as a pure string also doesn't seem ideal. Would love to discuss. 
 PS: I could also open a PR with my current state and we look at that if you like.

**Comment by AlbertMarashi** [comment]
@rellfy please review my PR
